(()=>{const root=document.querySelector('[data-acai-builder]');if(!root)return;
const sizes=[...root.querySelectorAll('[data-size]')],bases=[...root.querySelectorAll('[data-base]')],tops=[...root.querySelectorAll('[data-topping]')];
const title=root.querySelector('[data-build-title]'),topText=root.querySelector('[data-build-toppings]'),sizeText=root.querySelector('[data-build-size]'),priceText=root.querySelector('[data-build-price]'),bowl=root.querySelector('[data-preview-bowl]');
const money=n=>'Gs. '+Number(n).toLocaleString('es-PY');
const sync=()=>{const s=sizes.find(x=>x.classList.contains('active'))||sizes[0];const b=bases.find(x=>x.classList.contains('active'))||bases[0];const active=tops.filter(x=>x.classList.contains('active')).map(x=>x.dataset.topping);title.textContent=b.dataset.base;sizeText.textContent=s.dataset.size;bowl.style.background=b.dataset.tone;topText.textContent=active.length?active.join(' + '):'Sin toppings todavía';priceText.textContent=money(s.dataset.price);};
sizes.forEach(x=>x.addEventListener('click',()=>{sizes.forEach(y=>y.classList.remove('active'));x.classList.add('active');sync()}));
bases.forEach(b=>b.addEventListener('click',()=>{bases.forEach(x=>x.classList.remove('active'));b.classList.add('active');sync()}));
tops.forEach(t=>t.addEventListener('click',()=>{const active=tops.filter(x=>x.classList.contains('active'));if(!t.classList.contains('active')&&active.length>=3)active[0]?.classList.remove('active');t.classList.toggle('active');sync()}));
const art=document.querySelector('[data-tilt]');if(art&&!matchMedia('(prefers-reduced-motion: reduce)').matches){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.transform=`perspective(900px) rotateY(${x*5}deg) rotateX(${-y*4}deg)`});art.addEventListener('pointerleave',()=>art.style.transform='')}
sync()})();